services:
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: pass
      MARIADB_DATABASE: recordings
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - "data:/var/lib/mariadb"
volumes:
  data:

